### ISSUE TITLE
Unable to apply puppet manifest

### ISSUE THREAD

**Issue by qnm** [rapid7/puppet-logentries#6]
I've added this module to my puppet config using `librarian-puppet`, and am unable to apply.

```
  class { 'logentries':
    account_key => 'wefwefwefwef'
  }
```

When I do so, I get the error:

```
Error: Could not find dependent Package[logentries-daemon] for Apt::Source[logentries] at /etc/puppet/modules/logentries/manifests/repo/apt.pp:17
```

My puppet version

```
ch12:/etc/puppet# puppet --version
3.6.1
```

Am I missing something?

**Comment by gearoidof-r7** [comment]
Hey qnm, sorry for the delay in responding to this.

It would seem like the logentries daemon package wasn't available to download via apt on your machine, what OS are you installing on? Are there any other packages you install via apt (just to make sure it's our package specifically you can't install)

**Comment by reederz** [comment]
I was experiencing the same issue on Ubuntu 14.04. I've fixed it by including `logentries::agent` class alongside `logentries` class because `logentries::agent` installs `logentries-daemon` and `logentries` packages.
